### ISSUE TITLE
Can sorting be added to the configuration

### ISSUE THREAD

**Issue by IDWdam1ao** [Shiiho11/Pak.Mod.Manager#1]
Can you add sorting function? Without sorting, it feels uncomfortable to look at the file name
![image](https://github.com/Shiiho11/Pak.Mod.Manager/assets/109025769/b77c4629-4478-4d81-aaab-17459280f57e)

**Comment by Shiiho11** [comment]
还真没考虑过这个。
因为可以重命名，我本意是让用户自己管理的。
你的意思是希望mod config list按照name排序吗？
还是手动上移、下移list中的项目？

**Comment by IDWdam1ao** [comment]
四星的一起，五星的一起，按照名字排序 看起来会舒服很多

**Comment by Shiiho11** [comment]
考虑并不是每个人都希望这样排列（比如有人可能喜欢同一个角色4星和5星放一起），计划增加可以向上或者向下移动的按钮，点击按钮，list中当前config会向上或者向下移动一位。这样可以让用户按照自己的喜好排序。

**Comment by IDWdam1ao** [comment]
能排序就行，谢谢您!

**Comment by Shiiho11** [comment]
已完成，请检查最新的[Releases](https://github.com/Shiiho11/Pak.Mod.Manager/releases)。

**Comment by Shiiho11** [comment]
修复了一个bug。现在，当配置没有更改时，将不会写入配置文件。
